<script>
    let gridUrl = '<?php echo $this->getUrl('*/*/index'); ?>';
</script>

<?php echo $this->getChildHtml('addFilter_block')?>

<table>
    <thead>
        <tr>
            <?php foreach ($this->getTableHead() as $_th) : ?>
                <th onclick="sorting(this)" column="<?php echo $_th['column']; ?>"><?php echo $_th['label']; ?></th>
            <?php endforeach; ?>
            <th>View</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <input style="width: 70%;" type="text" name="ticket_id" id="ticket_id-filter">
            </td>
            <td>
                <input style="width: 70%;" type="text" name="title" id="title-filter">
            </td>
            <td>
                <input style="width: 70%;" type="text" name="description" id="description-filter">
            </td>
            <td>
                <input style="width: 70%;" type="text" name="admin_user" id="admin_user-filter">
            </td>
            <td>
                <input style="width: 70%;" type="text" name="assign_by" id="assign_by-filter">
            </td>
            <td>
                <input style="width: 70%;" type="text" name="status" id="status-filter">
            </td>
            <td>
                <input style="width: 70%;" type="text" name="priority" id="priority-filter">
            </td>
            <td>
                <button onclick="resetFilter()">Reset</button>
                <button onclick="searchFilter()">Search</button>
            </td>
        </tr>
        <?php foreach ($this->getTickets() as $tickets) : ?>
            <tr>
                <td><?php echo $tickets->getId(); ?></td>
                <td><?php echo $tickets->getTitle(); ?></td>
                <td><?php echo $tickets->getDescription(); ?></td>
                <td><?php echo $tickets->getAssignTo(); ?></td>
                <td><?php echo $tickets->getAssignBy(); ?></td>
                <td style="background-color: <?php echo $tickets->getStatusColor(); ?>;">
                    <?php echo $tickets->getStatusLabel(); ?>
                </td>
                <td><?php echo $tickets->getPriority(); ?></td>
                <td>
                    <a href="<?php echo $this->getUrl('*/*/view', ['id' => $tickets->getId()]); ?>">View</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<br>
<div>
    <?php if ($this->getTickets()) : ?>
        <?php for ($i = 1; $i <= ceil($this->getTickets()->getSize() / 5); $i++) : ?>
            <a href="<?php echo $this->getUrl('*/*/index', ['page' => $i]); ?>"><?php echo $i ?></a>
        <?php endfor; ?>
    <?php endif; ?>
</div>

<style>
    table,
    th,
    td {
        border: 1px solid;
        padding: 5px;
        text-align: center;
    }

    th {
        cursor: pointer;
    }
</style>