<div class="container">
    <h1>Ticket Details</h1>
    <table>
        <tr>
            <th>Ticket ID</th>
            <td id="ticket-id"><?php echo $this->getTicket()->getId(); ?></td>
        </tr>
        <tr>
            <th>Title</th>
            <td id="title"><?php echo $this->getTicket()->getTitle(); ?></td>
        </tr>
        <tr>
            <th>Description</th>
            <td id="description"><?php echo $this->getTicket()->getDescription(); ?></td>
        </tr>
        <tr>
            <th>Assign To</th>
            <td id="assign-to">
                <select onchange="updateTicket(this,'assignTo')" name="assign_to" id="assign_to">
                    <?php foreach ($this->getUsers() as $admin) : ?>
                        <option value="<?php echo $admin->getId(); ?>" <?php echo $this->getTicket()->getAssignToId() == $admin->getId() ? 'selected' : ''; ?>>
                            <?php echo $admin->getUsername(); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
        <tr>
            <th>Assign By</th>
            <td id="assign-by">
                <select onchange="updateTicket(this,'assignBy')" name="assign_by" id="assign_by">
                    <?php foreach ($this->getUsers() as $admin) : ?>
                        <option value="<?php echo $admin->getId(); ?>" <?php echo $this->getTicket()->getAssignById() == $admin->getId() ? 'selected' : ''; ?>>
                            <?php echo $admin->getUsername(); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
        <tr>
            <th>Priority</th>
            <td id="priority"><?php echo $this->getTicket()->getPriority(); ?></td>
        </tr>
        <tr>
            <th>Status</th>
            <td id="status">
                <select onchange="updateTicket(this, 'status')" name="status" id="status" style="background-color: <?php echo $this->getTicket()->getStatusColor(); ?>;">
                    <?php foreach ($this->getStatus() as $status) : ?>
                        <option style="background-color: white;" value=" <?php echo $status->getCode(); ?>" <?php echo $this->getTicket()->getStatusCode() == $status->getCode() ? 'selected' : ''; ?>>
                            <?php echo $status->getLabel(); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
        <tr>
            <th>Created Date</th>
            <td id="created-date"><?php echo $this->getTicket()->getCreatedDate(); ?></td>
        </tr>
        <tr>
            <th>Updated Date</th>
            <td id="updated-date"><?php echo $this->getTicket()->getUpdatedDate(); ?></td>
        </tr>
    </table>
</div>

<script>
    var ticketId = <?php echo $this->getTicket()->getId() ?>;
    var saveUrl = "<?php echo $this->getUrl('*/ticket/update') ?>";
</script>