<?php
$configPath = preg_replace('!\s+!', ' ', $this->getFilemanagerConfigData());
$paths = explode(" ", $configPath);
$basePath = Mage::getBaseUrl() . 'admin/filemanager/grid';
?>

<select name="folder_path" id="folder_path" onchange="changeFolderPath('<?php echo $basePath ?>')">
    <option value="">--- SELECT FOLDER PATH ---</option>
    <?php foreach ($paths as $path): ?>
        <option value="<?php echo $path; ?>">
            <?php echo strtoupper($path); ?>
        </option>
    <?php endforeach; ?>
</select>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>">
                <?php echo $this->getHeaderHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div id="filemanager-grid">
    <?php echo $this->getGridHtml() ?>
</div>